### PR TITLE
Without jQuery (WIP)

### PR DESCRIPTION
**Pull request by kbariotis**
This addresses #5.

I would like your opinions. There is that cloudinary plugin that is the only thing depending on jQuery.

What do you think?

### CODE REVIEW

**Comment by tibastral** [comment]
That's really cool ! How can we be sure it works on all browsers ?

**Comment by tibastral** [comment]
Is it retro-compatible (with the $ notation) ?
- Thibaut

**Comment by kbariotis** [comment]
> That's really cool ! How can we be sure it works on all browsers ?

We could setup a test suite using Karmajs or something equivalent. Not sure though, haven't done it before. 

> Is it retro-compatible (with the $ notation) ?

No, the purpose is to completely remove jQuery. But it can work with jQuery loaded in the page. Was that your question?

**Comment by tibastral** [comment]
We really need it to work with jQuery (with the $ notation).
What we could do is something like :

if (isDefined(jQuery)) {
  jQuery.define_markdownify({
    ...
  })
}

so people that use the $('totot').markdownify() will still be able to use it (even if we put a message saying that's deprecated).

And we also need Cloudinary to work.

As soon as that's ok, and it works among all browsers, I'll be happy to merge your PR.

**Comment by tibastral** [comment]
Closing that for now.

**Pull request closed without merging**
